on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: Test and get coverage
        run: |
          go test -v -covermode=count -coverprofile=coverage.out ./...
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
